### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [roberthovhannisyan/PhoneGap-Plugin-ListPicker#5]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...your plugin should be move to npm in the future...

**Comment by roberthovhannisyan** [comment]
Hi @bau720123,
I am aware of this process since I use PGB for my project as well. So it will be available the in the near future

**Comment by bau720123** [comment]
OK
Thanks @roberthovhannisym

**Comment by roberthovhannisyan** [comment]
@bau720123 
Now available on npmjs at https://www.npmjs.com/package/am.armsoft.plugins.listpicker

**Comment by bau720123** [comment]
thanks @roberthovhannisyan 
got it
