### ISSUE TITLE
Trigger the Holo design for Android

### ISSUE THREAD

**Issue by puntsok** [roberthovhannisyan/PhoneGap-Plugin-ListPicker#6]
Sorry for the simple question, but Is there a way to trigger the holo design for android in line with your example screenshot in the docs? It appears that I am still getting the old dialog design though my min sdk is set at 19

    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="22" />

![image](https://cloud.githubusercontent.com/assets/156741/8891812/c6dd015c-32fd-11e5-9d10-1d8bafdf0d27.png)

**Comment by roberthovhannisyan** [comment]
Hi @puntsok 
To achieve you can modify the application theme through android manifest file. If you are using PhoneGap Build you may consider adding following lines to your config.xml
```xml
    <gap:config-file platform="android" parent="/manifest">
        <application android:theme="@android:style/Theme.Holo.Light" />
    </gap:config-file>
```
I personally prefer using device's default theme by setting `android:theme` attribute to `@android:style/Theme.DeviceDefault`
